@startuml
!include <C4/C4_Context>

title App System Context Diagram

Person(customer, "Пользователь", "Пользователь управляет температурой", person)
System(app, " Система управления теплом в доме", "Предоставляет данные о температуре и позволяет ею управлять")

System_Ext(sensor, "Сенсор температуры", "Внешний прибор, установлен в доме пользователя")
System_Ext(warmer, "Отопление", "Управление отоплением")

Rel(customer, app, "Контроирует температуру")
Rel(sensor, app, "Регистрируется в системе")
Rel(app, sensor, "Запрос текущей температуры, управление температурой")
Rel(app, warmer, "Управляет отоплением")

@enduml